OnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Siniflar;
namespace OnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {
            var list = c.Departmanlars.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult departmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult departmanEkle(Departmanlar d)
        {
            c.Departmanlars.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult departmanGetir(int id)
        {
            var dep = c.Departmanlars.Find(id);
            return View("departmanGetir", dep);
        }

        public ActionResult departmanGuncelle(Departmanlar d)
        {
            var dp = c.Departmanlars.Find(d.DepartmanID);
            dp.Departman_ad = d.Departman_ad;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult departmanSil(int id)
        {
            var sil = c.Departmanlars.Find(id);
            c.Departmanlars.Remove(sil);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult departmanDetay(int id)
        {

            var detay = c.Personels.Where(x => x.Departmanid == id).ToList();

            var dpt = c.Departmanlars.Where(x => x.DepartmanID == id).Select(y => y.Departman_ad).FirstOrDefault();
            ViewBag.dgr = dpt;
            return View(detay);
        }

        public ActionResult departmanSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();

            var dp = c.Personels.Where(x => x.PersonelID == id).Select(y => y.Personel_ad).FirstOrDefault();
            ViewBag.per = dp;
            return View(degerler);
        }
    }
}

OnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Departmanlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DEPARTMAN LİSTESİ</h1>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>DAPARTMAN ADI</th>
        <th>DETAY</th>
        <th>DÜZENLE</th>
        <th>SİL</th>


    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@item.DepartmanID</td>
    <td>@item.Departman_ad</td>
    <td>
    <td><a href="/Departman/departmanDetay/@item.DepartmanID" class="btn btn-success">Detay</a></td>
    <td><a href="/Departman/departmanGetir/@item.DepartmanID" class="btn btn-warning">Düzenle</a></td>
    <td><a href="/Departman/departmanSil/@item.DepartmanID" class="btn btn-danger">Sil</a></td>
</tr>
    }
</table>
<a href="/Departman/departmanEkle/" class="btn btn-primary">Yeni Ekle</a>

OnlineTicariOtomasyon/Views/Departman/departmanDetay.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "departmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DEPARTMAN DETAY SAYFASI </h1> <span>DEPARTMAN: @ViewBag.dgr</span>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>RESİM</th>
        <th>SATIŞLAR</th>


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelID</td>
            <td>@item.Personel_ad</td>
            <td>@item.Personel_soyad</td>
            <td>@item.Personel_resim</td>
            <td><a href="/Departman/departmanSatis/@item.PersonelID" class="btn btn-success">SATIŞLAR</a></td>
         
        </tr>
    }
</table>
<a href="/Departman/departmanEkle/" class="btn btn-primary">Yeni Ekle</a>

OnlineTicariOtomasyon/Views/Departman/departmanEkle.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Departmanlar
@{
    ViewBag.Title = "departmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DEPARTMAN EKLEME SAYFASI</h1>

<form method="post">


    @Html.Label("DEPARTMAN ADI")
    @Html.TextBoxFor(x => x.Departman_ad, new { @class = "form-control" })
    <br />

   

    <button class="btn btn-primary">Ekle</button>
</form>

OnlineTicariOtomasyon/Views/Departman/departmanGetir.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Departmanlar
@{
    ViewBag.Title = "departmanGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>DEPARTMAN GÜNCELLEME SAYFASI</h2>
@using (Html.BeginForm("departmanGuncelle", "Departman", FormMethod.Post))
{
    <form method="post">
        @Html.HiddenFor(x => x.DepartmanID)
        @Html.Label("ÜRÜN ADI")
        @Html.TextBoxFor(x => x.Departman_ad, new { @class = "form-control" })

        <br />




        <button class="btn btn-warning">Güncelle</button>
    </form>
}

OnlineTicariOtomasyon/Views/Departman/departmanSatis.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "departmanSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>DEPARTMAN SATIŞ</h1> <span> Personel: @ViewBag.per</span>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>ÜRÜN</th>
        <th>MÜŞTERİ</th>
        <th>ADET</th>
        <th>FİYAT</th>
        <th>TOPLAM TUTAR</th>
        <th>TARİH</th>
        <th>YAZDIR</th>



    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@item.SatisID</td>
    <td>@item.Urunler.Urun_ad</td>
    <td>@item.Cariler.Cari_ad</td>
    <td>@item.Adet</td>
    <td>@item.Fiyat</td>
    <td>@item.ToplamTutar</td>
    <td>@item.Tarih</td>
    <td><a href="#" class="btn btn-info">YAZDIR</a></td>


</tr>
    }
</table>