OnlineTicariOtomasyon/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Personel_ad { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Personel_soyad { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string Personel_resim { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }

        public int Departmanid { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
    }
}

OnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Siniflar;
namespace OnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {

            var list = c.Personels.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult personelEkle()
        {
            List<SelectListItem> deger = (from x in c.Departmanlars.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.Departman_ad,
                                              Value = x.DepartmanID.ToString()
                                          }).ToList();

            ViewBag.dgr = deger.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult personelEkle(Personel p)
        {
           
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult personelGetir(int id)
        {
            List<SelectListItem> listele = (from x in c.Departmanlars
                                            select new SelectListItem
                                            {
                                                Text = x.Departman_ad,
                                                Value = x.DepartmanID.ToString()
                                            }).ToList();
            ViewBag.person = listele.ToList();

            var per = c.Personels.Find(id);
            return View("personelGetir", per);

        }

        public ActionResult personelGuncelle(Personel p)
        {
            var per = c.Personels.Find(p.PersonelID);
            per.Personel_ad = p.Personel_ad;
            per.Personel_soyad = p.Personel_soyad;
            per.Departmanid = p.Departmanid;
            per.Personel_resim = p.Personel_resim;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult personelSil(int id)
        {
            var per = c.Personels.Find(id);
            c.Personels.Remove(per);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

OnlineTicariOtomasyon/Views/personel/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>PERSONEL LİSTESİ</h1>


<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD SOYAD</th>
        <th>RESİM</th>
        <th>DEPARTMAN</th>
        <th>SATIŞ LİSTESİ</th>
        <th>DÜZENLE</th>
        <th>SİL</th>


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelID</td>
            <td>@item.Personel_ad &nbsp; @item.Personel_soyad</td>
            <td>@item.Personel_resim</td>
            <td>@item.Departmanlar.Departman_ad</td>
            <td><a href="/Departman/departmanSatis/@item.PersonelID" class="btn btn-success">Satış Listesi</a></td>
            <td><a href="/Personel/personelGetir/@item.PersonelID" class="btn btn-warning">Düzenle</a></td>
            <td><a href="/Personel/personelSil/@item.PersonelID" class="btn btn-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/Personel/personelEkle/" class="btn btn-primary">Yeni Ekle</a>

OnlineTicariOtomasyon/Views/personel/personelEkle.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "personelEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>PERSONEL EKLEME SAYFASI</h1>

<form method="post">
    @Html.Label("DEPARTMAN SEÇ")
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />

    @Html.Label("AD")
    @Html.TextBoxFor(x => x.Personel_ad, new { @class = "form-control" })
    <br />

    @Html.Label("SOYAD")
    @Html.TextBoxFor(x => x.Personel_soyad, new { @class = "form-control" })
    <br />

    @Html.Label("RESİM")
    @Html.TextBoxFor(x => x.Personel_resim, new { @class = "form-control" })
    <br />





    <button class="btn btn-primary">Ekle</button>
</form>

OnlineTicariOtomasyon/Views/personel/personelGetir.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "personelGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>PERSONEL GÜNCELLEME SAYFASI</h1>

@using (Html.BeginForm("personelGuncelle", "Personel", FormMethod.Post))
{
<form method="post">

    @Html.HiddenFor(x => x.PersonelID)
    @Html.Label("DEPARTMAN SEÇ")
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.person, new { @class = "form-control" })
    <br />
    @Html.Label("AD")
    @Html.TextBoxFor(x => x.Personel_ad, new { @class = "form-control" })
    <br />

    @Html.Label("SOYAD")
    @Html.TextBoxFor(x => x.Personel_soyad, new { @class = "form-control" })
    <br />

    @Html.Label("İLÇE")
    @Html.TextBoxFor(x => x.Personel_resim, new { @class = "form-control" })
    <br />





    <button class="btn btn-primary">Güncelle</button>
</form>

}