OnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Siniflar;
namespace OnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {
            var list = c.SatisHarekets.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult satisYap()
        {
            List<SelectListItem> urun = (from x in c.Urunlers
                                         select new SelectListItem
                                         {
                                             Text = x.Urun_ad,
                                             Value = x.UrunID.ToString()
                                         }).ToList();

            ViewBag.urn = urun;

            List<SelectListItem> musteri = (from x in c.Carilers
                                         select new SelectListItem
                                         {
                                             Text = x.Cari_ad + " " + x.Cari_soyad,
                                             Value = x.CariID.ToString()
                                         }).ToList();

            ViewBag.mst = musteri;

            List<SelectListItem> person = (from x in c.Personels
                                         select new SelectListItem
                                         {
                                             Text = x.Personel_ad + " " + x.Personel_soyad,
                                             Value = x.PersonelID.ToString()
                                         }).ToList();

            ViewBag.per = person;
            return View();
        }
        [HttpPost]
        public ActionResult satisYap(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortTimeString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult satisGetir(int id)
        {
            List<SelectListItem> uruns = (from x in c.Urunlers 
                                          select new SelectListItem
                                            {
                                                Text = x.Urun_ad,
                                                Value = x.UrunID.ToString()
                                            }).ToList();
                                            ViewBag.urn = uruns;

            List<SelectListItem> must = (from x in c.Carilers
                                          select new SelectListItem
                                          {
                                              Text = x.Cari_ad + " " + x.Cari_soyad,
                                              Value = x.CariID.ToString()
                                          }).ToList();
            ViewBag.mst = must;

            List<SelectListItem> person = (from x in c.Personels
                                          select new SelectListItem
                                          {
                                              Text = x.Personel_ad + " " + x.Personel_soyad,
                                              Value = x.PersonelID.ToString()
                                          }).ToList();
            ViewBag.per = person;

            var satis = c.SatisHarekets.Find(id);
            return View("satisGetir", satis);
        }

        public ActionResult satisGuncelle(SatisHareket s)
        {
            var satis = c.SatisHarekets.Find(s.SatisID);
            satis.Urunid = s.Urunid;
            satis.Cariid = s.Cariid;
            satis.Personelid = s.Personelid;
            satis.Fiyat = s.Fiyat;
            satis.Adet = s.Adet;
            satis.ToplamTutar = s.ToplamTutar;
            satis.Tarih = s.Tarih;
            c.SaveChanges();
            return RedirectToAction("Index");



        }

        public ActionResult urunListesi()
        {
            var urunList = c.Urunlers.ToList();
            return View(urunList);
        }

       
    }
}

OnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>SATIŞ LİSTESİ</h1>

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>ÜRÜN</th>
            <th>MÜŞTERİ</th>
            <th>PERSONEL</th>
            <th>FİYAT</th>
            <th>ADET</th>
            <th>TOPLAM TUTAR</th>
            <th>TARİH</th>
            <th>DÜZENLE</th>


        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SatisID</td>
            <td>@item.Urunler.Urun_ad</td>
            <td>@item.Cariler.Cari_ad  &nbsp; @item.Cariler.Cari_soyad</td>
            <td>@item.Personel.Personel_ad  &nbsp; @item.Personel.Personel_soyad</td>
            <td>@item.Fiyat</td>
            <td>@item.Adet</td>
            <td>@item.ToplamTutar</td>
            <td>@item.Tarih</td>
            <td><a href="/Satis/satisGetir/@item.SatisID" class="btn btn-warning">Düzenle</a></td>
        </tr>
    }
</table>
<a href="/Satis/satisYap/" class="btn btn-success">Yeni Satış Yap</a>


@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

OnlineTicariOtomasyon/Views/Satis/satisGetir.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "satisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>SATIŞ DÜZENLEME SAYFASI</h1>


@using (Html.BeginForm("satisGuncelle", "Satis", FormMethod.Post))
{ 
<form method="post">

    @Html.HiddenFor(x => x.SatisID)
    @Html.Label("ÜRÜN")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.urn, new { @class = "form-control" })
    <br />
    @Html.Label("MÜŞTERİ")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.mst, new { @class = "form-control" })
    <br />

    @Html.Label("PERSONEL")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.per, new { @class = "form-control" })
    <br />

    @Html.Label("FİYAT")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />

    @Html.Label("ADET")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.Label("TOPLAM TUTAR")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.Label("TARİH")
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />




    <button class="btn btn-primary">Güncelle</button>
</form>

}

OnlineTicariOtomasyon/Views/Satis/satisYap.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "satisYap";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>YENİ SATIŞ YAP</h1>

<form method="post">
    @Html.Label("ÜRÜN SEÇ")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.urn, new { @class = "form-control" })
    <br />

    @Html.Label("MÜŞTERİ SEÇ")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.mst, new { @class = "form-control" })
    <br />

    @Html.Label("PERSONEL SEÇ")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.per, new { @class = "form-control" })
    <br />

    @Html.Label("FİYAT")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />

    @Html.Label("ADET")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />

    @Html.Label("TOPLAM TUTAR")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />

    @Html.Label("TARİH")
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />




    <button class="btn btn-primary">Ekle</button>
</form>

OnlineTicariOtomasyon/Views/Satis/urunListesi.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Urunler>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Ürün Id</th>

                <th>Adı</th>

                <th>Marka</th>

                <th>Stok</th>


                <th>Alış Fiyat</th>

                <th>Satış Fiyat</th>

                <th>Durum</th>

                <th>Kategori</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.UrunID</td>

                    <td>@x.Urun_ad</td>

                    <td>@x.Urun_Marka</td>

                    <td>@x.Urun_stok</td>

                    <td>@x.Urun_alis_fiyat</td>

                    <td>@x.Urun_satis_fiyat</td>

                    <td>@x.Urun_durum</td>

                    <td>@x.Kategori.Kategori_ad</td>

                </tr>

            }



        </tbody>

    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>
</body>
</html>