OnlineTicariOtomasyon/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Siniflar;
namespace OnlineTicariOtomasyon.Controllers
{
    public class DefaultController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {
            var listele = c.Kategoris.ToList();
            return View(listele);
        }

        [HttpGet]
        public ActionResult kategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult kategoriEkle(Kategori k)
        {
            c.Kategoris.Add(k);
            c.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public ActionResult kategoriSil(int id)
        {
            var degerler = c.Kategoris.Find(id);
            c.Kategoris.Remove(degerler);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult kategoriGetir(int id)
        {
            var kategori = c.Kategoris.Find(id);
            return View("kategoriGetir", kategori);
        }

        public ActionResult kategoriGuncelle(Kategori k)
        {
            var kategori = c.Kategoris.Find(k.KategoriID);
            kategori.Kategori_ad = k.Kategori_ad;
            c.SaveChanges();
            return RedirectToAction("Index");

        }
       
    }
}

OnlineTicariOtomasyon/Views/Default/Index.cshtml
@using OnlineTicariOtomasyon.Models.Siniflar
@model List<Kategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>KATEGORİLER</h1>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ AD</th>
        <th>DÜZENLE</th>
        <th>SİL</th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@item.KategoriID</td>
    <td>@item.Kategori_ad</td>
    <td><a href="/Default/kategoriGetir/@item.KategoriID" class="btn btn-warning">Düzenle</a></td>
    <td><a href="/Default/kategoriSil/@item.KategoriID" class="btn btn-danger">Sil</a></td>
</tr>
    }
</table>

<a href="/Default/kategoriEkle/" class="btn btn-primary">Yeni Ekle</a>

OnlineTicariOtomasyon/Views/Default/kategoriEkle.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "kategoriEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>KATEGORİ EKLEME SAYFASI</h1>
<form method="post">
    @Html.Label("KATEGORİ ADI")
    @Html.TextBoxFor(x=>x.Kategori_ad, new { @class="form-control"})
    <br />

    <button class="btn btn-primary">Ekle</button>
</form>

OnlineTicariOtomasyon/Views/Default/kategoriGetir.cshtml
@model OnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "kategoriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>KATEGORİ GÜNCELLEME SAYFASI</h1>
@using (Html.BeginForm("kategoriGuncelle", "Default", FormMethod.Post))
{
    <form method="post">
    
        @Html.Label("KATEGORİ ADI")
        @Html.TextBoxFor(x => x.Kategori_ad, new { @class = "form-control" })
        @Html.HiddenFor(x=>x.KategoriID)
        <br />

        <button class="btn btn-warning">Güncelle</button>
    </form>
}